spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/aybashim
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.exclude.keywords=Mehmet Faruk Gül